#!/usr/bin/env bash

V=$(cat ./VERSION)
TARGET="./target/$V"

mkdir -p $TARGET

echo "Building for v$V"

GOOS=darwin GOARCH=amd64 go build -o "$TARGET/secrets-darwin-amd64" main.go
GOOS=windows GOARCH=amd64 go build -o "$TARGET/secrets-windows-amd64.exe" main.go
GOOS=linux GOARCH=amd64 go build -o "$TARGET/secrets-linux-amd64" main.go

echo "Binaries built to ./target"
